### PR TITLE
Support phpstan v2.1.18

### LINKED ISSUE #1418: [Bug]: Type coverage plugin - Too few arguments to function PHPStan\Analyser\RuleErrorTransformer
### What Happened

After updating phpstan to 2.1.18 (previously using 2.1.17) I get the below error when trying to run `php artisan test --type-coverage`. I couldn't see an issues tab on the type coverage plugin so am raising here.

```
ArgumentCountError 

  Too few arguments to function PHPStan\Analyser\RuleErrorTransformer::__construct(), 0 passed in /var/www/html/vendor/pestphp/pest-plugin-type-coverage/src/TestCaseForTypeCoverage.php on line 113 and exactly 1 expected

  at phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/RuleErrorTransformer.php:40
     36▕ final class RuleErrorTransformer
     37▕ {
     38▕     private Parser $parser;
     39▕     private Differ $differ;
  ➜  40▕     public function __construct(
     41▕         #[AutowiredParameter('@currentPhpVersionPhpParser')]
     42▕         Parser $parser
     43▕     )
     44▕     {
```

### How to Reproduce

Run `composer update` to update phpstan to 2.1.18 and then run `php artisan test --type-coverage` 

### Sample Repository

_No response_

### Pest Version

v3.8.2

### PHP Version

8.4.3

### Operation System

Linux

### Notes

_No response_

### PR DESCRIPTION
**Pull request by faissaloux**
Fixes https://github.com/pestphp/pest/issues/1418

### CODE REVIEW

File: src/TestCaseForTypeCoverage.php [hunk 1]
```diff
@@ -110,7 +110,7 @@ public function gatherAnalyserErrors(array $files): array
         }
 
         $actualErrors = $analyserResult->getUnorderedErrors();
-        $ruleErrorTransformer = new RuleErrorTransformer;
+        $ruleErrorTransformer = self::getContainer()->getByType(RuleErrorTransformer::class);
```
Comment (MrPunyapal) [inline src/TestCaseForTypeCoverage.php:113]: this fixes the issue

File: src/TestCaseForTypeCoverage.php [hunk 2]
```diff
@@ -121,12 +121,12 @@ public function gatherAnalyserErrors(array $files): array
                 $ruleErrors = $rule->processNode($node, $scope);
                 foreach ($ruleErrors as $ruleError) {
                     if ($this->ignored($ruleError)) {
-                        $this->ignoredErrors[] = $ruleErrorTransformer->transform($ruleError, $scope, $nodeType, $node->getLine());
+                        $this->ignoredErrors[] = $ruleErrorTransformer->transform($ruleError, $scope, [], $node);
```
Comment (MrPunyapal) [inline src/TestCaseForTypeCoverage.php:124]: why these changes required?

File: src/TestCaseForTypeCoverage.php [hunk 3]
```diff
@@ -121,12 +121,12 @@ public function gatherAnalyserErrors(array $files): array
...
 
                         continue;
                     }
 
-                    $actualErrors[] = $ruleErrorTransformer->transform($ruleError, $scope, $nodeType, $node->getLine());
+                    $actualErrors[] = $ruleErrorTransformer->transform($ruleError, $scope, [], $node);
```
Comment (MrPunyapal) [inline src/TestCaseForTypeCoverage.php:129]: why these changes required?
