### ISSUE TITLE
Symfony\Component\Finder\Exception\DirectoryNotFoundException while executing command

### ISSUE THREAD

**Issue by Fxdpt** [pestphp/pest-plugin-type-coverage#25]
While trying to running the command 

`./vendor/bin/pest --type-coverage`

I've  got the following error:

![image](https://github.com/pestphp/pest-plugin-type-coverage/assets/52032862/e00df121-38c1-495d-b8db-786237097c04)

Maybe I'm missing some configuration but I've just follow the documentation

**Comment by eman1986** [comment]
I'm also running into this, according to the documentation, it should just work.

**Comment by pl38** [comment]
I also have this issue

**Comment by mallardduck** [comment]
@nunomaduro  - I experienced this on a brand new project after running the init command `./vendor/bin/pest --init`.

This seems to be caused because the init added `./app` and `./src` to `phpunit.xml`. And the `--type-coverage` flag seems to use the `sources` from that file to know where to scan. After deleting the `./app` line in my project where it doesn't exist the error is resolved.

Even after that I am running into new errors which seem to be related to PHPstan version compatibility issues. To fix those it seems that you must be on exactly `phpstan` version `1.11.6`, so I added this to my composer file:

```
"phpstan/phpstan": "1.11.6"
```

Otherwise I get:

```
  Too few arguments to function PHPStan\Analyser\NodeScopeResolver::__construct(), 26 passed in <PROJECT>/vendor/pestphp/pest-plugin-type-coverage/src/PHPStanAnalyser.php on line 54 and exactly 27 expected
```

This is caused by this change: https://github.com/phpstan/phpstan-src/commit/04f8636e6577cbcaefc944725eed74c0d7865ead

So technically users can probably work with `1.11.7` but not anything higher. Potentially the composer deps of this package need to be adjusted to pin a specific version as the highest? I.e. `<=1.11.7` instead of: https://github.com/pestphp/pest-plugin-type-coverage/blob/2.x/composer.json#L18

So there's two issues when using this by default:

- The init command source paths cause errors;
- The phpstan internal code that this library uses changed signatures.
